config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
# read all
  get    "articles",          to: "articles#index"

  #create new task
  get    "articles/new",      to: "articles#new"

  # find a task
  get    "articles/:id",      to: "articles#show", as: "article"


  post   "articles",          to: "articles#create"

  #edit a new task
  get    "articles/:id/edit", to: "articles#edit", as: "editarticle"

  patch  "articles/:id",      to: "articles#update"

  #delete a task
  delete "articles/:id",      to: "articles#destroy"

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  def index
    @articles = Article.all
  end

  def show
    @article = Article.find(params[:id])
  end

  def new
    @article = Article.new
  end

  def create
    @article = Article.new(article_params)
    @article.save
    redirect_to articles_path(@articles)
  end

  def edit
    @article = Article.find(params[:id])
  end

  def update
    @article = Article.find(params[:id])
    @article.update(article_params)
    redirect_to articles_path(@articles)
  end

  def destroy
    @article = Article.find(params[:id])
    @article.destroy
    redirect_to articles_path(@articles)
  end

  private

  def article_params
    params.require(:article).permit(:title, :content)
  end

  def set_article
    @article = Article.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/_form.html.erb
<%= form_for(@article) do |f| %>
  <div>
  <%= f.label :title %>
  <%= f.text_field :title %>
  </div>

  <div>
  <%= f.label :content %>
  <%= f.text_field :content %>
  </div>

  <div>
  <%= f.submit %>
  </div>

<% end %>

app/views/articles/edit.html.erb
<%= render 'form' %>

app/views/articles/index.html.erb
<h1>WIKINIMOUS</h1>


<% @articles.each do |article| %>
  <h2><%= link_to article.title, article_path(article)%></h2>
  <p><%= article.content %></p>
<% end %>

<p><%= link_to "New Article", articles_new_path%></p>

app/views/articles/new.html.erb
<%= render 'form' %>

app/views/articles/show.html.erb
<h1><%= @article.title %></h1>
<h2><%= @article.content%></h2>

<p><%= link_to "All Articles", articles_path %></p>
<p><%= link_to "Edit articles", editarticle_path %></p>
<p><%= link_to "Delete artile", article_path(@article), method: :delete %></p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsWikinimous</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>